//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventWebService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventEntities : DbContext
    {
        public InventEntities()
            : base("name=InventEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InventoryPart> InventoryParts { get; set; }
        public virtual DbSet<InvPartInStock> InvPartInStocks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
