//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvPartInStock
    {
        public string serial_no { get; set; }
        public string part_no { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public Nullable<System.DateTime> manuf_date { get; set; }
        public Nullable<System.DateTime> stock_in_date { get; set; }
    
        public virtual InventoryPart InventoryPart { get; set; }
    }
}
